game:
  winner-timeout: 10
  game-over-timeout: 15

server:
  servlet:
    session:
      timeout: 1209600 # 1209600 seconds = 14 days
  port: 80

###
#   Database Settings
###
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true
