game:
  winner-timeout: 10
  game-over-timeout: 15

server:
  servlet:
    session:
      timeout: 1209600 # 1209600 seconds = 14 days
  port: 80

###
#   Database Settings
###
spring:
  datasource:
    url:
    platform: mysql
    username:
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

  ###
  #   H2 Settings
  ###
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false

  output:
    ansi:
      enabled: ALWAYS

